version: 1.0.0.{build}
os: WMF 5
environment:
  psgkey:
    secure: RMszZiCE/plk4eBiwX+qxsFc4e07dNqaYhklRq4pLwrAei6lch4pvjq03MiHuwqn
hosts:
  test1.example.com: 10.1.1.1
  test2.example.com: 192.168.1.1
install: 
  - cinst -y pester
build: off
test_script:
    - ps: |
        $testResultsFile = ".\TestsResults.xml"
        $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) { 
            throw "$($res.FailedCount) tests failed."
        }
deploy_script:
  - ps: |
      Install-PackageProvider -Name NuGet -Force 
      $manifest = Join-Path -Path $pwd -ChildPath "TAK\tak.psd1"
      (Get-Content $manifest -Raw) -Replace("1\.0\.0\.\d{1}", $env:APPVEYOR_BUILD_VERSION) | Out-File $manifest
      $PublishPath = Join-Path -Path $pwd -ChildPath TAK
      Publish-Module -NugetApiKey $($env:psgkey) -Path $PublishPath